# Generated by Django 2.2.13 on 2020-07-21 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200721_1118'),
        ('movie', '0002_searchresult_searchtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='搜寻关键字')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('result', models.BooleanField(verbose_name='查询是否成功')),
                ('num', models.CharField(max_length=3, verbose_name='查询的数量')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.User', verbose_name='用户')),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
