# Generated by Django 2.2.13 on 2020-07-21 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20200721_1825'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='searchrecord',
            table='search_record',
        ),
    ]
